parameters:
#    pendulage_accueil.example.class: Pendulage\Bundle\AccueilBundle\Example

services:
#    pendulage_accueil.example:
#        class: %pendulage_accueil.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
